# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SpeedFlux Home Assistant add-on
version: "0.0.1"
slug: speedflux
description: SpeedFlux add-on
url: "https://github.com/hy3n4/addons-speedflux/tree/main/speedflux"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/hy3n4/{arch}-addon-speedflux"
